### ISSUE TITLE
Question: Is it possible to use with Github Actions?

### ISSUE THREAD

**Issue by pb1919** [jackcoded/newman-reporter-slackmsg#19]
Hi,
I have a Github Actions workflow using a newman action.  I would like to use this reporter to provide automated feedback.  I realise I need to change the reporters to include slackmsg, but am not sure how to include the relevant options for token, channel, etc.  Any help is very much appreciated!

```
      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          delayRequest: 100
          collection: ./test/newman/postman_collection.json
          environment: ./test/newman/postman_environment.json
          reporters: cli
          folder: specifc tests
```
